### ISSUE TITLE
No module named fields Error

### ISSUE THREAD

**Issue by somesmart** [dulacp/django-accounting#4]
I am getting this error message on this line:

`from django_select2.fields import ( `

from 
`/usr/local/lib/python2.7/dist-packages/accounting/apps/people/forms.py in <module>`

as you can see I am on python2.7 as well as django 1.8 so not sure if that's the issue. 

Thanks!

**Comment by somesmart** [comment]
Same issue on django 1.11. Haven't tried on python 3 yet

**Comment by dulaccc** [comment]
Thanks for the feedback, I'm looking into it!

**Comment by somesmart** [comment]
I played around with it some more and found that it was due to a change in django_select2. If you change your call to
`django_select2.forms.ModelSelect2MultipleWidget`
and
`django_select2.forms.ModelSelect2Widget`

it should work.

**Comment by dulacp** [comment]
Back on this issue.
I only tested the project on Python 3.3 and 3.4.

I wasn't able to reproduce your error, but thanks for mentionning it so that others can find it in the search engine.

Best regards

**Comment by sduraiengineer** [comment]
Can you please retry again? I am facing the same problem agaub, 

Can please give the django_select2 version

**Comment by beltiras** [comment]
I have this problem.  Was installing from https://github.com/dulacp/Accountant
